import { Cohort, Student, LessonPlan, TaskItem, CefrMilestone, TeachingSession, TeachingClaim } from '../types';

export const initialTeacher = {
  id: 'teacher-1',
  email: 'sarah.jenkins@classque.edu',
  name: 'Ms. Sarah Jenkins',
  schoolName: 'Garuda International Language Academy',
  schoolLogoUrl: '',
  defaultHourlyRate: 150000, // Rp 150.000 / hr
  currency: 'IDR',
  languagePreference: 'id' as const,
  themePreference: 'light' as const,
};

export const initialCohorts: Cohort[] = [
  {
    id: 'cohort-1',
    teacherId: 'teacher-1',
    name: 'Cambridge Flyers A2',
    cefrLevel: 'A2',
    scheduleDays: ['Mon', 'Wed', 'Fri'],
    startTime: '14:30',
    durationMinutes: 60,
    roomOrLink: 'Room 204 (Building B)',
    hourlyRateOverride: 175000,
    isActive: true,
  },
  {
    id: 'cohort-2',
    teacherId: 'teacher-1',
    name: 'Cambridge Starters A1',
    cefrLevel: 'A1',
    scheduleDays: ['Mon', 'Wed'],
    startTime: '13:15',
    durationMinutes: 60,
    roomOrLink: 'Room 102',
    isActive: true,
  },
  {
    id: 'cohort-3',
    teacherId: 'teacher-1',
    name: 'IELTS Intensive Prep',
    cefrLevel: 'B2',
    scheduleDays: ['Tue', 'Thu'],
    startTime: '17:00',
    durationMinutes: 90,
    roomOrLink: 'Virtual Lab (Meet)',
    hourlyRateOverride: 200000,
    isActive: true,
  },
];

export const initialStudents: Student[] = [
  {
    id: 'student-1',
    cohortId: 'cohort-1',
    fullName: 'Liam Wong',
    nickname: 'Liam',
    gender: 'M',
    guardianName: 'Mrs. Linda Wong',
    guardianPhone: '+6281234567890',
    notes: 'Very enthusiastic speaker, working on past tense irregular verbs.',
    strengths: 'Confident spoken interaction, good listening comprehension',
    growthAreas: 'Spelling in writing assignments',
    isActive: true,
  },
  {
    id: 'student-2',
    cohortId: 'cohort-1',
    fullName: 'Aisha Khan',
    nickname: 'Aisha',
    gender: 'F',
    guardianName: 'Mr. Tariq Khan',
    guardianPhone: '+6281298765432',
    notes: 'Excels in reading and grammar exercises.',
    strengths: 'Rich vocabulary, fast reader',
    growthAreas: 'Needs encouragement for spontaneous speaking',
    isActive: true,
  },
  {
    id: 'student-3',
    cohortId: 'cohort-1',
    fullName: 'Eara Marn',
    nickname: 'Eara',
    gender: 'F',
    guardianName: 'Mrs. Dewi Marn',
    guardianPhone: '+6281311223344',
    notes: 'Consistent worker, loves storytelling activities.',
    strengths: 'Creative storytelling, clear pronunciation',
    growthAreas: 'Prepositions of place',
    isActive: true,
  },
  {
    id: 'student-4',
    cohortId: 'cohort-1',
    fullName: 'Nanfa Shama',
    nickname: 'Nanfa',
    gender: 'M',
    guardianName: 'Mr. Hadi Shama',
    guardianPhone: '+6281555667788',
    notes: 'Quick learner, responds well to gamified drills.',
    strengths: 'Fast reflexes in vocab games',
    growthAreas: 'Punctuation in paragraphs',
    isActive: true,
  },
  {
    id: 'student-5',
    cohortId: 'cohort-1',
    fullName: 'Budi Santoso',
    nickname: 'Budi',
    gender: 'M',
    guardianName: 'Ibu Ratna Santoso',
    guardianPhone: '+6281777889900',
    notes: 'Needs occasional pacing reminders.',
    strengths: 'Friendly team player in group work',
    growthAreas: 'Concentration during long reading texts',
    isActive: true,
  },
  {
    id: 'student-6',
    cohortId: 'cohort-2',
    fullName: 'Siti Rahma',
    nickname: 'Siti',
    gender: 'F',
    guardianName: 'Ibu Maryam',
    guardianPhone: '+6281233445566',
    notes: 'Eager beginner, loves phonics songs.',
    strengths: 'High motivation, rapid phonics absorption',
    growthAreas: 'Alphabet writing stroke order',
    isActive: true,
  },
];

export const initialLessonPlans: LessonPlan[] = [
  {
    id: 'lesson-1',
    teacherId: 'teacher-1',
    cohortId: 'cohort-1',
    title: 'Unit 4: Prehistoric Animals & Past Events',
    topic: 'Dinosaurs, Fossils, and Simple Past Tense',
    cefrLevel: 'A2',
    durationMinutes: 60,
    warmUp: 'Flashcard dinosaur guessing game (5 mins) to activate schema and energy.',
    presentation: 'Introduce key vocabulary (fossil, extinct, herbivore, carnivore) and past irregular verbs (ate, lived, hunted).',
    practice: 'Pair work: Worksheet page 24. Match the dinosaur facts with the correct past verb forms.',
    production: 'Students invent their own dinosaur and describe in 4 sentences what it looked like and what it ate.',
    wrapUp: 'Exit ticket: Each student shares 1 fact using past simple before leaving.',
    vocabulary: [
      { word: 'extinct', pos: 'adj', definitionEn: 'No longer existing in the world', definitionId: 'Punah / sudah tidak ada lagi', example: 'Dinosaurs became extinct millions of years ago.' },
      { word: 'fossil', pos: 'noun', definitionEn: 'Preserved remains of ancient organisms', definitionId: 'Fosil / sisa makhluk purba yang membatu', example: 'The scientist found a T-Rex fossil.' },
      { word: 'herbivore', pos: 'noun', definitionEn: 'An animal that feeds on plants', definitionId: 'Hewan pemakan tumbuhan', example: 'Brachiosaurus was a giant herbivore.' },
      { word: 'carnivore', pos: 'noun', definitionEn: 'An animal that feeds on other animals', definitionId: 'Hewan pemakan daging', example: 'Velociraptor was a fast carnivore.' },
    ],
    grammarFocus: 'Past Simple with irregular verbs (eat/ate, see/saw, find/found)',
    materialsLinks: ['https://drive.google.com/example-worksheet.pdf'],
    homework: 'Activity Book page 18 (Exercises 1 to 3)',
    isTemplate: false,
  },
];

export const initialTasks: TaskItem[] = [
  {
    id: 'task-1',
    teacherId: 'teacher-1',
    cohortId: 'cohort-1',
    title: "Grade Assignment 'Flyers Unit 4'",
    priority: 'urgent',
    dueDate: '2026-09-05',
    isCompleted: false,
  },
  {
    id: 'task-2',
    teacherId: 'teacher-1',
    cohortId: 'cohort-2',
    title: "Review 'Level 3 Materials' for Cambridge Starters",
    priority: 'high',
    dueDate: '2026-09-05',
    isCompleted: false,
  },
  {
    id: 'task-3',
    teacherId: 'teacher-1',
    cohortId: 'cohort-1',
    title: 'Prepare CFA2 printable flashcards',
    priority: 'medium',
    dueDate: '2026-09-06',
    isCompleted: false,
  },
  {
    id: 'task-4',
    teacherId: 'teacher-1',
    cohortId: 'cohort-1',
    title: 'Send WhatsApp progress summary to Liam Wong guardian',
    priority: 'medium',
    dueDate: '2026-09-07',
    isCompleted: false,
  },
];

export const initialCefrMilestones: CefrMilestone[] = [
  {
    id: 'ms-1',
    cefrLevel: 'A2',
    skillCategory: 'spoken_production',
    code: 'A2.SP.1',
    descriptionEn: 'Describe past events and activities using simple phrases',
    descriptionId: 'Menceritakan kegiatan lampau dengan frasa sederhana',
    canDoStatementEn: 'Can give a short, basic description of events and past activities.',
    canDoStatementId: 'Mampu memberikan deskripsi singkat dan sederhana mengenai kejadian masa lampau.',
  },
  {
    id: 'ms-2',
    cefrLevel: 'A2',
    skillCategory: 'spoken_interaction',
    code: 'A2.SI.1',
    descriptionEn: 'Ask and answer simple questions about past habits',
    descriptionId: 'Bertanya dan menjawab pertanyaan sederhana tentang kebiasaan lampau',
    canDoStatementEn: 'Can ask and answer simple questions on familiar topics.',
    canDoStatementId: 'Mampu bertanya dan menjawab pertanyaan sederhana tentang topik umum.',
  },
  {
    id: 'ms-3',
    cefrLevel: 'A2',
    skillCategory: 'reading',
    code: 'A2.RD.1',
    descriptionEn: 'Understand short factual texts containing familiar vocabulary',
    descriptionId: 'Memahami teks faktual pendek yang memuat kosakata umum',
    canDoStatementEn: 'Can understand short, simple texts containing the highest frequency vocabulary.',
    canDoStatementId: 'Mampu memahami teks pendek sederhana dengan kosakata frekuensi tinggi.',
  },
  {
    id: 'ms-4',
    cefrLevel: 'A2',
    skillCategory: 'writing',
    code: 'A2.WR.1',
    descriptionEn: 'Write short simple notes and messages relating to matters of immediate need',
    descriptionId: 'Menulis catatan dan pesan pendek sederhana sesuai kebutuhan',
    canDoStatementEn: 'Can write short, simple notes and messages relating to everyday matters.',
    canDoStatementId: 'Mampu menulis catatan dan pesan pendek mengenai hal sehari-hari.',
  },
];

export const initialSessions: TeachingSession[] = [
  {
    id: 'session-prev-1',
    teacherId: 'teacher-1',
    cohortId: 'cohort-2',
    lessonPlanId: 'lesson-1',
    sessionDate: '2026-09-05',
    startTime: '13:15',
    endTime: '14:15',
    durationMinutes: 60,
    hourlyRate: 150000,
    totalClaimAmount: 150000,
    status: 'completed',
    scratchpadNotes: 'Great energy today on phonics games.',
  },
];

export const initialClaims: TeachingClaim[] = [
  {
    id: 'claim-1',
    teacherId: 'teacher-1',
    claimPeriod: '2026-09',
    claimNumber: 'CLM-202609-001',
    totalSessions: 18,
    totalHours: 27.0,
    baseAmount: 4050000,
    allowanceAmount: 200000,
    totalClaimAmount: 4250000,
    currency: 'IDR',
    status: 'draft',
  },
];
